services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: donspace-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - donspace-postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default:
    name: donspace-net
    external: true

volumes:
  donspace-postgres-data:
